site_name: Solaris Wiki

theme: readthedocs

extra_css: [
    _styles/style.css
]

repo_url: 'https://github.com/mike-eason/solaris'

nav:
  - Welcome: 'index.md'
  - 'guide.md'
  - 'overview.md'
  - 'infrastructure.md'
  - 'technologies.md'
